const config = {
  BASE_API_DOMAIN: process.env.REACT_APP_BASE_API_DOMAIN,
  ENDPOINT_GENERATION: process.env.REACT_APP_ENDPOINT_GENERATION,
  ENDPOINT_SPECIES: process.env.REACT_APP_ENDPOINT_SPECIES,
  ENDPOINT_REGION: process.env.REACT_APP_ENDPOINT_REGION,
  ENDPOINT_POKEDEX: process.env.REACT_APP_ENDPOINT_POKEDEX,
  ENDPOINT_VERSION: process.env.REACT_APP_ENDPOINT_VERSION,
  ENDPOINT_TYPE: process.env.REACT_APP_ENDPOINT_TYPE,
  ENDPOINT_COLOR: process.env.REACT_APP_ENDPOINT_COLOR,
  ENDPOINT_EGG_GROUP: process.env.REACT_APP_ENDPOINT_EGG_GROUP,
  ENDPOINT_HABITAT: process.env.REACT_APP_ENDPOINT_HABITAT,
  ENDPOINT_SHAPE: process.env.REACT_APP_ENDPOINT_SHAPE,
  ARTWORK:
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/",
};

export default config;
