const config = {
  BASE_API_DOMAIN: process.env.REACT_APP_BASE_API_DOMAIN,
  ENDPOINT_GENERATION: process.env.REACT_APP_ENDPOINT_GENERATION,
  ENDPOINT_POKEDEX: process.env.REACT_APP_ENDPOINT_POKEDEX,
  ENDPOINT_VERSION: process.env.REACT_APP_ENDPOINT_VERSION,
  ENDPOINT_BERRY: process.env.REACT_APP_ENDPOINT_BERRY,
};

export default config;
